### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by JetMeta**
1. in func CLV_CleanupWindowData should cleanup pListData->m_pColumns & pListData->m_piColumnOrder 2. in func CPSK_DestroySkin should cleanup pSkin->mpl_pFocus

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hi there.

Thanks for the PR. I'm not sure if I should merge being that I actually don't use this for a long time and I didn't expect anyone else to use it to be honest :P

I don't even know if the upstream project still exists.

**Comment by JetMeta** [comment]
I had noticed that last commit happened six years ago. Sorry for disturbing you.

**Comment by XhmikosR** [comment]
I can merge it if you think it's right. Just don't expect much from this fork. :)

**Comment by JetMeta** [comment]
I think it's better to keep current state. Thanks.

**Pull request closed without merging**
